# Generated by ChatGPT on 2026-03-29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=512, unique=True)),
                ('device_type', models.CharField(choices=[('web', 'Web'), ('android', 'Android'), ('ios', 'iOS')], default='web', max_length=20)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='userdevicetoken',
            index=models.Index(fields=['user', 'is_active'], name='core_userdev_user_id_b4e62a_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevicetoken',
            index=models.Index(fields=['last_seen_at'], name='core_userdev_last_se_0c62d1_idx'),
        ),
    ]
