# Generated by Django 5.1.1 on 2026-05-04 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userdevicetoken'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userdevicetoken',
            new_name='core_userde_user_id_2e07f9_idx',
            old_name='core_userdev_user_id_b4e62a_idx',
        ),
        migrations.RenameIndex(
            model_name='userdevicetoken',
            new_name='core_userde_last_se_213497_idx',
            old_name='core_userdev_last_se_0c62d1_idx',
        ),
    ]
