# Generated by Django 5.1.1 on 2025-10-24 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_enhanced_leave_management'),
        ('finance', '0002_adjustment_reminderlog_residentrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenditures', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='category',
            field=models.CharField(choices=[('electricity', 'Electricity'), ('groceries', 'Groceries'), ('maintenance', 'Maintenance'), ('advance_return', 'Advance Return'), ('other', 'Other')], max_length=50),
        ),
    ]
