# Generated by Django 5.1.1 on 2025-10-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_add_advance_return_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='category',
            field=models.CharField(choices=[('electricity', 'Electricity'), ('groceries', 'Groceries'), ('maintenance', 'Maintenance'), ('advance_return', 'Advance Return'), ('rent', 'Rent'), ('vegetables', 'Vegetables'), ('gas_bill', 'Gas Bill'), ('drinking_water_bill', 'Drinking Water Bill'), ('municipal_water_bill', 'Municipal Water Bill'), ('milk', 'Milk'), ('chicken', 'Chicken'), ('paneer', 'Paneer'), ('other', 'Other')], max_length=50),
        ),
    ]
