# Generated by Django 5.1.1 on 2025-10-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_expenditure_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='from_date',
            field=models.DateField(blank=True, help_text='Billing period start date', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='to_date',
            field=models.DateField(blank=True, help_text='Billing period end date', null=True),
        ),
    ]
