# Generated by Django 5.1.1 on 2025-10-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_payment_from_date_payment_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('fee', 'Fee'), ('advance', 'Advance'), ('daywise', 'Day-wise')], default='fee', max_length=10),
        ),
    ]
