# Generated by Django 5.1.1 on 2025-10-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(help_text='This date is referred to as the payment date or transaction date.'),
        ),
    ]
