# Generated by Django 5.1.1 on 2025-11-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cash_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cash component when mode is UPI+CASH', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='upi_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='UPI component when mode is UPI+CASH', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('upi_cash', 'UPI+CASH')], default='upi', max_length=10),
        ),
    ]
