# Generated by Django 5.1.1 on 2025-11-06 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_payment_cash_amount_payment_upi_amount_and_more'),
        ('pgadmin', '0013_pg_allow_custom_leave_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='category',
            field=models.CharField(blank=True, choices=[('electricity', 'Electricity'), ('groceries', 'Groceries'), ('maintenance', 'Maintenance'), ('advance_return', 'Advance Return'), ('rent', 'Rent'), ('vegetables', 'Vegetables'), ('gas_bill', 'Gas Bill'), ('drinking_water_bill', 'Drinking Water Bill'), ('municipal_water_bill', 'Municipal Water Bill'), ('milk', 'Milk'), ('chicken', 'Chicken'), ('paneer', 'Paneer'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ExpenditureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('is_default', models.BooleanField(default=False, help_text='Default categories cannot be deleted')),
                ('display_order', models.IntegerField(default=0)),
                ('pg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenditure_categories', to='pgadmin.pg')),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'unique_together': {('pg', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='expenditure',
            name='category_custom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenditures', to='finance.expenditurecategory'),
        ),
    ]
