# Generated by Django 5.1.1 on 2025-11-06 17:09

from django.db import migrations
from django.utils.text import slugify


def populate_default_categories(apps, schema_editor):
    """Create default categories for all PGs based on the legacy CATEGORY_CHOICES."""
    PG = apps.get_model('pgadmin', 'PG')
    ExpenditureCategory = apps.get_model('finance', 'ExpenditureCategory')
    
    # Default categories from the legacy CATEGORY_CHOICES
    DEFAULT_CATEGORIES = [
        ('Electricity', 'electricity', 1),
        ('Groceries', 'groceries', 2),
        ('Maintenance', 'maintenance', 3),
        ('Advance Return', 'advance_return', 4),
        ('Rent', 'rent', 5),
        ('Vegetables', 'vegetables', 6),
        ('Gas Bill', 'gas_bill', 7),
        ('Drinking Water Bill', 'drinking_water_bill', 8),
        ('Municipal Water Bill', 'municipal_water_bill', 9),
        ('Milk', 'milk', 10),
        ('Chicken', 'chicken', 11),
        ('Paneer', 'paneer', 12),
        ('Other', 'other', 13),
    ]
    
    for pg in PG.objects.all():
        for name, slug, order in DEFAULT_CATEGORIES:
            ExpenditureCategory.objects.get_or_create(
                pg=pg,
                slug=slug,
                defaults={
                    'name': name,
                    'is_default': True,
                    'display_order': order,
                }
            )


def reverse_populate(apps, schema_editor):
    """Remove all default categories on reverse migration."""
    ExpenditureCategory = apps.get_model('finance', 'ExpenditureCategory')
    ExpenditureCategory.objects.filter(is_default=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_add_expenditure_category'),
        ('pgadmin', '0001_initial'),  # Ensure PG model is available
    ]

    operations = [
        migrations.RunPython(populate_default_categories, reverse_populate),
    ]
