# Generated by Django 5.1.1 on 2025-11-06 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_populate_default_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='category_custom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenditures', to='finance.expenditurecategory'),
        ),
    ]
