# Generated by Django 5.1.1 on 2025-11-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_change_category_delete_to_set_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='share_type',
            field=models.CharField(choices=[('1', 'Single'), ('2', '2-Sharing'), ('3', '3-Sharing'), ('4', '4-Sharing'), ('5', '5-Sharing'), ('6', '6-Sharing'), ('7', '7-Sharing'), ('8', '8-Sharing'), ('9', '9-Sharing'), ('10', '10-Sharing')], max_length=2),
        ),
    ]
