# Generated by Django 5.1.1 on 2025-11-20 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_extend_share_types_to_10'),
        ('pgadmin', '0013_pg_allow_custom_leave_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adjustment_type', models.CharField(choices=[('discount', 'Discount'), ('increment', 'Increment')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to discount or increment', max_digits=10)),
                ('duration_type', models.CharField(choices=[('continuous', 'Continuous'), ('one_month', 'One Month'), ('multiple_months', 'Multiple Months')], max_length=16)),
                ('selected_months', models.JSONField(blank=True, default=list, help_text='List of YYYY-MM strings for specific months')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_monthly_adjustments', to=settings.AUTH_USER_MODEL)),
                ('pg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_adjustments', to='pgadmin.pg')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_adjustments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
