# Generated by Django 5.1.1 on 2026-02-15 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0026_whatsapp_invite_fields'),
        ('finance', '0013_monthlyadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(blank=True, help_text='Linked booking for this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='bookings.booking'),
        ),
    ]
