# Generated by Django 5.1.1 on 2025-09-09 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgadmin', '0002_alter_pgadmin_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pgadmin',
            unique_together=set(),
        ),
    ]
