# Generated by Django 5.1.1 on 2025-09-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgadmin', '0003_alter_pgadmin_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20),
        ),
    ]
