# Generated by Django on 2025-09-22
from django.db import migrations, models


def gen_initial_slugs(apps, schema_editor):
    PG = apps.get_model('pgadmin', 'PG')
    from django.utils.text import slugify
    for pg in PG.objects.all():
        if not getattr(pg, 'slug', None):
            base = slugify(pg.name) or 'pg'
            slug = base
            n = 2
            while PG.objects.filter(slug=slug).exclude(pk=pg.pk).exists():
                slug = f"{base}-{n}"
                n += 1
            pg.slug = slug
            pg.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('pgadmin', '0004_pg_phone'),
    ]

    operations = [
        # Stage 1: add field as nullable and not-unique to allow data backfill without constraint issues (SQLite table copy)
        migrations.AddField(
            model_name='pg',
            name='slug',
            field=models.SlugField(blank=True, null=True, max_length=200, unique=False),
        ),
        # Stage 2: backfill slugs for existing rows
        migrations.RunPython(gen_initial_slugs, migrations.RunPython.noop),
        # Stage 3: enforce uniqueness and non-null
        migrations.AlterField(
            model_name='pg',
            name='slug',
            field=models.SlugField(blank=True, null=False, max_length=200, unique=True),
        ),
    ]
