# Generated by Django 5.1.1 on 2025-10-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgadmin', '0006_pg_referral_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg',
            name='past_joining_date_allowed',
            field=models.BooleanField(default=False, help_text='Allow selecting a joining date in the past for quick bookings.'),
        ),
    ]
