# Generated by Django 5.1.1 on 2025-10-20 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_alter_referralcredit_id'),
        ('pgadmin', '0007_pg_past_joining_date_allowed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Brief title of the complaint', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the issue')),
                ('category', models.CharField(choices=[('maintenance', 'Maintenance'), ('cleanliness', 'Cleanliness'), ('food', 'Food'), ('wifi', 'WiFi/Internet'), ('electricity', 'Electricity'), ('water', 'Water Supply'), ('security', 'Security'), ('noise', 'Noise'), ('other', 'Other')], default='other', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('solved', 'Solved'), ('not_solved', 'Not Solved'), ('closed', 'Closed')], default='open', max_length=15)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the complaint was marked as solved', null=True)),
                ('booking', models.ForeignKey(blank=True, help_text='Active booking reference', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='bookings.booking')),
                ('pg', models.ForeignKey(help_text='PG where the complaint was raised', on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='pgadmin.pg')),
                ('resolved_by', models.ForeignKey(blank=True, help_text='Admin who resolved the complaint', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_complaints', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who raised the complaint', on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(help_text='Comment or update on the complaint')),
                ('is_internal', models.BooleanField(default=False, help_text='Internal notes (not visible to tenant)')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pgadmin.complaint')),
                ('user', models.ForeignKey(help_text='Admin who added the comment', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['pg', 'status'], name='pgadmin_com_pg_id_3b3f35_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['user', 'status'], name='pgadmin_com_user_id_460001_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['created_at'], name='pgadmin_com_created_4ff5b7_idx'),
        ),
    ]
