# Generated by Django 5.1.1 on 2025-10-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgadmin', '0008_complaint_complaintcomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('solved', 'Solved')], default='open', max_length=15),
        ),
    ]
