# Generated by Django 5.1.1 on 2025-10-20 17:49

from django.db import migrations


def update_old_statuses(apps, schema_editor):
    """
    Update complaints with removed statuses:
    - 'not_solved' -> 'in_progress'
    - 'closed' -> 'solved'
    """
    Complaint = apps.get_model('pgadmin', 'Complaint')
    
    # Update 'not_solved' to 'in_progress'
    Complaint.objects.filter(status='not_solved').update(status='in_progress')
    
    # Update 'closed' to 'solved'
    Complaint.objects.filter(status='closed').update(status='solved')


def reverse_update(apps, schema_editor):
    """Reverse migration - convert back to old statuses if needed"""
    # This is optional - you can leave it as pass if you don't want to reverse
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pgadmin', '0009_alter_complaint_status'),
    ]

    operations = [
        migrations.RunPython(update_old_statuses, reverse_update),
    ]
