# Generated by Django 5.1.1 on 2025-10-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgadmin', '0010_update_complaint_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg',
            name='notice_period',
            field=models.PositiveIntegerField(default=30, help_text='Notice period in days required before leaving.'),
        ),
    ]
