# Generated by Django 5.1.1 on 2025-10-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgadmin', '0011_add_notice_period_to_pg'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg',
            name='daywise_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fee per day for day-wise/short-term bookings.', max_digits=10),
        ),
    ]
