# Generated by Django 5.1.1 on 2025-10-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgadmin', '0012_pg_daywise_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg',
            name='allow_custom_leave_date',
            field=models.BooleanField(blank=True, default=True, help_text='Allow tenants to select a custom leaving date when requesting to leave the PG.'),
        ),
    ]
