# Generated by Django 5.1.1 on 2025-12-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgadmin', '0013_pg_allow_custom_leave_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg',
            name='whatsapp_invite_link',
            field=models.URLField(blank=True, help_text='WhatsApp group invite link for this PG.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pg',
            name='whatsapp_invite_message',
            field=models.TextField(blank=True, help_text='Custom message to send with the WhatsApp group invite link.', null=True),
        ),
    ]
