# Generated by Django 5.1.1 on 2025-12-31 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgadmin', '0014_whatsapp_invite_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PGAdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('can_view_employees', models.BooleanField(default=False, help_text='Can view employee details for their PG')),
                ('can_delete_payments', models.BooleanField(default=False, help_text='Can delete payment entries')),
                ('can_edit_payments', models.BooleanField(default=False, help_text='Can edit payment entries')),
                ('pg_admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='pgadmin.pgadmin')),
            ],
            options={
                'verbose_name': 'PG Admin Permission',
                'verbose_name_plural': 'PG Admin Permissions',
            },
        ),
    ]
