# Generated by Django 5.1.1 on 2025-12-31 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgadmin', '0015_pgadminpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgadminpermission',
            name='can_edit_employees',
            field=models.BooleanField(default=False, help_text='Can create, edit and delete employees for their PG'),
        ),
    ]
