# Generated by Django 5.1.1 on 2025-12-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgadmin', '0016_pgadminpermission_can_edit_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgadminpermission',
            name='can_edit_applications',
            field=models.BooleanField(default=False, help_text='Can edit tenant applications for their PG'),
        ),
    ]
