# Generated by Django 5.1.1 on 2025-12-31 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgadmin', '0017_add_can_edit_applications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OldTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(help_text='Full name of the tenant', max_length=255)),
                ('father_name', models.CharField(blank=True, help_text="Father's name", max_length=255)),
                ('mother_name', models.CharField(blank=True, help_text="Mother's name", max_length=255)),
                ('email', models.EmailField(help_text='Email address', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Phone number', max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, help_text='WhatsApp number', max_length=20)),
                ('address', models.TextField(blank=True, help_text='Permanent address')),
                ('room_no', models.CharField(blank=True, help_text='Room number during stay', max_length=20)),
                ('bed_no', models.PositiveSmallIntegerField(blank=True, help_text='Bed/share number during stay', null=True)),
                ('joining_date', models.DateField(blank=True, help_text='Date when tenant joined', null=True)),
                ('leaving_date', models.DateField(blank=True, help_text='Date when tenant left', null=True)),
                ('leaving_reason', models.TextField(blank=True, help_text='Reason for leaving')),
                ('advance_paid', models.DecimalField(decimal_places=2, default=0, help_text='Advance amount paid', max_digits=10)),
                ('advance_returned', models.DecimalField(decimal_places=2, default=0, help_text='Advance amount returned', max_digits=10)),
                ('original_booking_id', models.IntegerField(blank=True, help_text='Original booking ID before deletion', null=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True, help_text='When this record was archived')),
                ('archived_by', models.ForeignKey(blank=True, help_text='Admin who archived/deleted the booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_tenants', to=settings.AUTH_USER_MODEL)),
                ('original_user', models.ForeignKey(blank=True, help_text='Original user account (if still exists)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_tenant_records', to=settings.AUTH_USER_MODEL)),
                ('pg', models.ForeignKey(help_text='PG where the tenant resided', on_delete=django.db.models.deletion.CASCADE, related_name='old_tenants', to='pgadmin.pg')),
            ],
            options={
                'ordering': ['-archived_at'],
                'indexes': [models.Index(fields=['pg', 'archived_at'], name='pgadmin_old_pg_id_7db896_idx'), models.Index(fields=['joining_date'], name='pgadmin_old_joining_204b9d_idx'), models.Index(fields=['leaving_date'], name='pgadmin_old_leaving_b7da2f_idx'), models.Index(fields=['full_name'], name='pgadmin_old_full_na_5c1182_idx')],
            },
        ),
    ]
