# Generated by Django 5.1.1 on 2026-01-25 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgadmin', '0018_add_old_tenant_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgadminpermission',
            name='can_delete_confirmed_bookings',
            field=models.BooleanField(default=False, help_text='Can delete confirmed/approved bookings'),
        ),
        migrations.CreateModel(
            name='ComplaintMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('file_url', models.URLField(help_text='Google Drive URL of the uploaded file', max_length=500)),
                ('file_name', models.CharField(blank=True, help_text='Original filename', max_length=255)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('thumbnail_url', models.URLField(blank=True, help_text='Thumbnail URL for images/videos', max_length=500)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='pgadmin.complaint')),
            ],
            options={
                'verbose_name': 'Complaint Media',
                'verbose_name_plural': 'Complaint Media',
                'ordering': ['created_at'],
            },
        ),
    ]
