# Generated by Django 5.1.1 on 2026-05-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgadmin', '0019_add_complaint_media_and_delete_booking_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldtenant',
            name='aadhaar_file_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='oldtenant',
            name='aadhaar_file_url_2',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='oldtenant',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='oldtenant',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oldtenant',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oldtenant',
            name='education',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='oldtenant',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text='Emergency contact number', max_length=20),
        ),
        migrations.AddField(
            model_name='oldtenant',
            name='father_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='oldtenant',
            name='food_pref',
            field=models.CharField(blank=True, choices=[('veg', 'Veg'), ('nonveg', 'Non-Veg')], max_length=10),
        ),
        migrations.AddField(
            model_name='oldtenant',
            name='has_vehicle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oldtenant',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married')], max_length=10),
        ),
        migrations.AddField(
            model_name='oldtenant',
            name='mother_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='oldtenant',
            name='occupation',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('employee', 'Employee')], max_length=20),
        ),
        migrations.AddField(
            model_name='oldtenant',
            name='org_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='oldtenant',
            name='org_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='oldtenant',
            name='selfie_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='oldtenant',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='oldtenant',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
