# Generated by Django 5.1.1 on 2026-07-10 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgadmin', '0020_oldtenant_aadhaar_file_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wa_id', models.CharField(max_length=30)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('pg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_contacts', to='pgadmin.pg')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('unread_count', models.PositiveIntegerField(default=0)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='pgadmin.whatsappcontact')),
                ('pg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_conversations', to='pgadmin.pg')),
            ],
            options={
                'ordering': ['-last_message_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('message_type', models.CharField(default='text', max_length=30)),
                ('text', models.TextField(blank=True)),
                ('media_id', models.CharField(blank=True, max_length=255)),
                ('media_url', models.URLField(blank=True, max_length=1000)),
                ('status', models.CharField(default='received', max_length=30)),
                ('section', models.CharField(blank=True, max_length=40)),
                ('provider_timestamp', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='pgadmin.whatsappconversation')),
                ('pg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='pgadmin.pg')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_whatsapp_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['provider_timestamp', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payload_hash', models.CharField(max_length=64, unique=True)),
                ('phone_number_id', models.CharField(blank=True, max_length=100)),
                ('processed', models.BooleanField(default=False)),
                ('payload', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('pg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_webhook_events', to='pgadmin.pg')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhatsAppCloudConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False)),
                ('api_base_url', models.URLField(default='https://graph.facebook.com', max_length=500)),
                ('api_version', models.CharField(default='v25.0', max_length=20)),
                ('messages_endpoint', models.CharField(blank=True, help_text='Optional full endpoint. Use {phone_number_id} as a placeholder, or leave blank to derive it.', max_length=700)),
                ('phone_number_id', models.CharField(blank=True, max_length=100, null=True)),
                ('business_account_id', models.CharField(blank=True, max_length=100)),
                ('display_phone_number', models.CharField(blank=True, max_length=30)),
                ('template_language', models.CharField(default='en_US', max_length=20)),
                ('monthly_template_name', models.CharField(blank=True, max_length=255)),
                ('messages_template_name', models.CharField(blank=True, max_length=255)),
                ('leaving_template_name', models.CharField(blank=True, max_length=255)),
                ('compliance_template_name', models.CharField(blank=True, max_length=255)),
                ('access_token_encrypted', models.TextField(blank=True)),
                ('verify_token_encrypted', models.TextField(blank=True)),
                ('app_secret_encrypted', models.TextField(blank=True)),
                ('enable_monthly_dashboard', models.BooleanField(default=False)),
                ('enable_whatsapp_messages', models.BooleanField(default=False)),
                ('enable_leaving_page', models.BooleanField(default=False)),
                ('enable_compliance_page', models.BooleanField(default=False)),
                ('pg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_cloud_config', to='pgadmin.pg')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('phone_number_id__isnull', False), models.Q(('phone_number_id', ''), _negated=True)), fields=('phone_number_id',), name='unique_whatsapp_cloud_phone_number_id')],
            },
        ),
        migrations.AddIndex(
            model_name='whatsappcontact',
            index=models.Index(fields=['pg', 'wa_id'], name='pgadmin_wha_pg_id_eef84e_idx'),
        ),
        migrations.AddConstraint(
            model_name='whatsappcontact',
            constraint=models.UniqueConstraint(fields=('pg', 'wa_id'), name='unique_whatsapp_contact_per_pg'),
        ),
        migrations.AddConstraint(
            model_name='whatsappconversation',
            constraint=models.UniqueConstraint(fields=('pg', 'contact'), name='unique_whatsapp_conversation_per_pg'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['pg', 'conversation', 'created_at'], name='pgadmin_wha_pg_id_03e33e_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['pg', 'status'], name='pgadmin_wha_pg_id_95cea9_idx'),
        ),
    ]
