# Generated by Django 5.1.1 on 2025-11-02 18:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pgadmin', '0013_pg_allow_custom_leave_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('emergency_contact', models.CharField(blank=True, help_text='Emergency contact number', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('selfie', models.ImageField(blank=True, null=True, upload_to='employee/selfies/')),
                ('aadhaar', models.FileField(blank=True, help_text='Aadhaar card document', null=True, upload_to='employee/aadhaar/')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('joining_date', models.DateField()),
                ('salary_date', models.DateField(help_text='Monthly salary payment date')),
                ('work_notes', models.TextField(blank=True, help_text='Work notes, responsibilities, etc.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is employee currently working?')),
                ('pg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='pgadmin.pg')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('advance', 'Advance Given'), ('salary', 'Salary Paid'), ('deduction', 'Deduction'), ('bonus', 'Bonus'), ('adjustment', 'Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive for payments to employee (salary, bonus), Negative for advances/deductions', max_digits=10)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='employee.employee')),
            ],
            options={
                'verbose_name': 'Employee Ledger Entry',
                'verbose_name_plural': 'Employee Ledger Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
