# Generated by Django 5.1.1 on 2025-11-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='aadhaar',
            field=models.FileField(blank=True, help_text='Aadhaar card document', null=True, upload_to='employees/aadhaar/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to='employees/selfies/'),
        ),
    ]
