# Generated by Django 5.1.1 on 2025-11-02 19:30

import employee.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employeeattendance_employeedocument_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='aadhaar',
            field=models.FileField(blank=True, help_text='Aadhaar card document', null=True, storage=employee.storage.EmployeeAadhaarStorage, upload_to='employees/aadhaar/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='selfie',
            field=models.ImageField(blank=True, null=True, storage=employee.storage.EmployeeSelfieStorage, upload_to='employees/selfies/'),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='document_file',
            field=models.FileField(storage=employee.storage.EmployeeGoogleDriveStorage, upload_to='employees/documents/'),
        ),
    ]
