from django.urls import path
from . import views


urlpatterns = [
    path('my/', views.my_pg, name='pg_my'),
    path('my/<int:pg_id>/qr.pdf', views.quick_booking_qr_pdf, name='pg_quick_booking_qr_pdf'),
    path('tenants/', views.tenants, name='pg_tenants'),
    path('tenants/export/', views.tenants_export_excel, name='pg_tenants_export'),
    path('rooms/', views.rooms_list, name='pg_rooms'),
    path('rooms/new/', views.room_create, name='pg_room_create'),
    path('rooms/<int:pk>/edit/', views.room_edit, name='pg_room_edit'),
    path('rooms/<int:pk>/shares/', views.room_shares, name='pg_room_shares'),
    path('vehicles/search/', views.vehicle_search, name='pg_vehicle_search'),
    path('applications/', views.resident_applications, name='pg_resident_applications'),
    path('bookings/pending/', views.bookings_pending, name='pg_bookings_pending'),
    path('bookings/<int:booking_id>/approve/', views.booking_approve, name='pg_booking_approve'),
    path('bookings/<int:booking_id>/reject/', views.booking_reject, name='pg_booking_reject'),
    path('bookings/<int:booking_id>/leave/', views.booking_leave_direct, name='pg_booking_leave_direct'),
    path('bookings/<int:booking_id>/swap/', views.booking_swap_room, name='pg_booking_swap_room'),
    path('bookings/<int:booking_id>/swap/options/rooms/', views.booking_swap_rooms_api, name='pg_booking_swap_rooms_api'),
    path('bookings/<int:booking_id>/swap/options/rooms/<int:room_id>/shares/', views.booking_swap_shares_api, name='pg_booking_swap_shares_api'),
    path('bookings/<int:booking_id>/application-email/', views.application_email_send, name='pg_application_email_send'),
    path('booking/<int:booking_id>/join-date/', views.booking_joining_update, name='pg_booking_joining_update'),
    path('leaving/', views.leaving_requests, name='pg_leaving_requests'),
    path('leaving/<int:booking_id>/confirm/', views.leaving_confirm, name='pg_leaving_confirm'),
    path('leaving/<int:booking_id>/reject/', views.leaving_reject, name='pg_leaving_reject'),
    path('leaving/<int:booking_id>/delete/', views.leaving_delete, name='pg_leaving_delete'),
    path('applications/<int:app_id>/confirm/', views.application_confirm, name='pg_application_confirm'),
    path('applications/<int:app_id>/reject/', views.application_reject, name='pg_application_reject'),
    path('applications/<int:app_id>/refill/', views.application_refill_request, name='pg_application_refill'),
    path('applications/<int:app_id>/referral/', views.application_update_referral, name='pg_application_referral'),
    path('applications/<int:app_id>/pdf/', views.application_pdf, name='pg_application_pdf'),
    path('referrals/', views.pg_referrals, name='pg_referrals'),
]
