from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()
"""
Django settings for pgms project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'dev-insecure-secret-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*' if DEBUG else '').split(',') if os.getenv('ALLOWED_HOSTS') else ['*' if DEBUG else 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    # 3rd party
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'crispy_forms',
    'crispy_bootstrap5',

    # local apps
    'core',
    'accounts',
    'pgadmin',
    'bookings',
    'finance',
    'siteadmin',
    'employee',
    'advertisements',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'accounts.middleware.HideAllauthMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Database optimization middleware (must be near the end)
    'core.middleware.SQLiteOptimizationMiddleware',
    'core.middleware.DatabaseConnectionMiddleware',
    'core.middleware.DatabaseRetryMiddleware',
]

ROOT_URLCONF = 'pgms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.unread_counts',
                'core.context_processors.pg_context',
                'core.context_processors.google_client',
            ],
        },
    },
]

WSGI_APPLICATION = 'pgms.wsgi.application'
SITE_ID = 1

# Auth / allauth
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]
LOGIN_REDIRECT_URL = 'dashboard'
ACCOUNT_LOGOUT_REDIRECT_URL = 'home'
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.getenv('GOOGLE_CLIENT_ID', ''),
            'secret': os.getenv('GOOGLE_CLIENT_SECRET', ''),
            'key': ''
        },
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    }
}


LANGUAGE_CODE = 'en-us'

# Enforce Asia/Kolkata timezone across all environments
TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

# Django 5 defaults to built-in formatting; USE_L10N is deprecated

USE_TZ = True


SOCIALACCOUNT_LOGIN_ON_GET = True

# Custom adapters to auto-link Google accounts to existing email users
ACCOUNT_ADAPTER = 'accounts.adapters.PGAccountAdapter'
SOCIALACCOUNT_ADAPTER = 'accounts.adapters.PGSocialAccountAdapter'

# Crispy
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            'timeout': 30,  # Increase timeout from default 5 to 30 seconds
            'init_command': (
                "PRAGMA journal_mode=WAL;"  # Write-Ahead Logging for better concurrency
                "PRAGMA synchronous=NORMAL;"  # Faster writes while maintaining safety
                "PRAGMA cache_size=-64000;"  # 64MB cache (negative = KB)
                "PRAGMA temp_store=MEMORY;"  # Store temp tables in memory
                "PRAGMA busy_timeout=30000;"  # 30 second busy timeout
            ),
        },
        'CONN_MAX_AGE': 600,  # Keep connections alive for 10 minutes
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

# Remove duplicate i18n/timezone block; values set above


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    }
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email (placeholder - configure via .env)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')

# Media (for local dev; files may later sync to Google Drive)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Google Drive (service account) configuration
GOOGLE_SERVICE_ACCOUNT_FILE = os.getenv('GOOGLE_SERVICE_ACCOUNT_FILE', '')
GOOGLE_DRIVE_FOLDER_SELFIES = os.getenv('GOOGLE_DRIVE_FOLDER_SELFIES', '')
GOOGLE_DRIVE_FOLDER_AADHAAR = os.getenv('GOOGLE_DRIVE_FOLDER_AADHAAR', '')
GOOGLE_DRIVE_FOLDER_EMPLOYEE = os.getenv('GOOGLE_DRIVE_FOLDER_EMPLOYEE', '')
GOOGLE_DRIVE_MAKE_PUBLIC = os.getenv('GOOGLE_DRIVE_MAKE_PUBLIC', 'False') == 'True'
# Optional: user OAuth token file for personal Google accounts (no Workspace)
GOOGLE_OAUTH_TOKEN_FILE = os.getenv('GOOGLE_OAUTH_TOKEN_FILE', str(BASE_DIR / 'token.json'))
