# Generated by Django 5.1.1 on 2025-12-31 23:23

import advertisements.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pgadmin', '0018_add_old_tenant_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Advertisement image (will be cropped/resized before upload)', upload_to=advertisements.models.advertisement_image_path)),
                ('title', models.CharField(blank=True, help_text='Optional title for the image', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description displayed on the image')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this image in the carousel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement_images', to='pgadmin.pg')),
            ],
            options={
                'verbose_name': 'Advertisement Image',
                'verbose_name_plural': 'Advertisement Images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvertisementSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_enabled', models.BooleanField(default=True, help_text='Enable or disable the image carousel on user dashboard')),
                ('text_enabled', models.BooleanField(default=True, help_text='Enable or disable the scrolling text on user dashboard')),
                ('carousel_interval', models.PositiveIntegerField(default=5000, help_text='Time between slides in milliseconds (minimum 1000ms)', validators=[django.core.validators.MinValueValidator(1000)])),
                ('text_scroll_speed', models.PositiveIntegerField(default=50, help_text='Scrolling text speed (higher = slower, range 10-200)', validators=[django.core.validators.MinValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement_settings', to='pgadmin.pg')),
            ],
            options={
                'verbose_name': 'Advertisement Settings',
                'verbose_name_plural': 'Advertisement Settings',
            },
        ),
        migrations.CreateModel(
            name='AdvertisementText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Text to display in the scrolling marquee')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this text in the marquee')),
                ('text_color', models.CharField(default='#ffffff', help_text='Text color (hex format, e.g., #ffffff)', max_length=7)),
                ('background_color', models.CharField(default='#1e3a5f', help_text='Background color (hex format, e.g., #1e3a5f)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement_texts', to='pgadmin.pg')),
            ],
            options={
                'verbose_name': 'Advertisement Text',
                'verbose_name_plural': 'Advertisement Texts',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
