# Generated by Django 5.1.1 on 2026-01-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementsettings',
            name='carousel_enabled',
            field=models.BooleanField(default=False, help_text='Enable or disable the image carousel on user dashboard'),
        ),
        migrations.AlterField(
            model_name='advertisementsettings',
            name='text_enabled',
            field=models.BooleanField(default=False, help_text='Enable or disable the scrolling text on user dashboard'),
        ),
    ]
