# Generated by Django 5.1.1 on 2025-09-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_pg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
