# Generated by Django 5.1.1 on 2025-09-09 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_joining_date'),
        ('pgadmin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('father_name', models.CharField(blank=True, max_length=255)),
                ('father_phone', models.CharField(blank=True, max_length=20)),
                ('mother_name', models.CharField(blank=True, max_length=255)),
                ('mother_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('date_of_admission', models.DateField(blank=True, null=True)),
                ('food_pref', models.CharField(blank=True, choices=[('veg', 'Veg'), ('nonveg', 'Non-Veg')], max_length=10)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married')], max_length=10)),
                ('education', models.CharField(blank=True, max_length=255)),
                ('occupation', models.CharField(blank=True, choices=[('student', 'Student'), ('employee', 'Employee')], max_length=20)),
                ('org_name', models.CharField(blank=True, max_length=255)),
                ('org_address', models.TextField(blank=True)),
                ('aadhaar_number', models.CharField(blank=True, max_length=20)),
                ('selfie_url', models.URLField(blank=True)),
                ('aadhaar_file_url', models.URLField(blank=True)),
                ('signature_url', models.URLField(blank=True)),
                ('decl_valuables', models.BooleanField(default=False)),
                ('decl_notice', models.BooleanField(default=False)),
                ('decl_deposit', models.BooleanField(default=False)),
                ('decl_truth', models.BooleanField(default=False)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='bookings.booking')),
                ('pg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resident_applications', to='pgadmin.pg')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resident_applications', to='bookings.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resident_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
