# Generated by Django 5.1.1 on 2025-09-09 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_residentapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residentapplication',
            name='signature_url',
        ),
    ]
