# Generated by Django 5.1.1 on 2025-09-10 19:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_booking_leaving_confirmed_date'),
        ('pgadmin', '0003_alter_pgadmin_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'approved'])), fields=('room', 'share_no', 'user'), name='uniq_active_booking_same_share_user'),
        ),
    ]
