# Generated by Django 5.1.1 on 2025-09-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_residentapplication_status_applicationstatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentapplication',
            name='aadhaar_file_url_2',
            field=models.URLField(blank=True),
        ),
    ]
