# Generated by Django 5.1.1 on 2025-10-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_residentapplication_referred_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcredit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
