# Generated by Django 5.1.1 on 2025-10-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_alter_referralcredit_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentapplication',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp number (can be same as phone)', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='joining_date',
            field=models.DateField(blank=True, help_text='Date tenant actually moved in; used to calculate rent days.', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_date',
            field=models.DateField(blank=True, help_text='Monthly rent due date (day of month); defaults to joining date.', null=True),
        ),
    ]
