# Generated by Django 5.1.1 on 2025-10-24 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_add_whatsapp_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='advance_eligible',
            field=models.BooleanField(default=True, help_text='Eligible for advance refund based on notice period'),
        ),
        migrations.AddField(
            model_name='booking',
            name='advance_returned',
            field=models.BooleanField(default=False, help_text='Advance amount returned by PG admin'),
        ),
        migrations.AddField(
            model_name='booking',
            name='advance_returned_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='advance_returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='leaving_initiated_at',
            field=models.DateTimeField(blank=True, help_text='When user requested to leave', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='leaving_reason',
            field=models.TextField(blank=True, help_text="User's reason for leaving"),
        ),
        migrations.CreateModel(
            name='RoomSwap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_share_no', models.PositiveSmallIntegerField()),
                ('to_share_no', models.PositiveSmallIntegerField()),
                ('effective_date', models.DateField(help_text='Date when swap takes effect')),
                ('is_future_swap', models.BooleanField(default=False, help_text='Swap scheduled for future based on leaving date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(help_text='The booking that is being swapped', on_delete=django.db.models.deletion.CASCADE, related_name='swaps', to='bookings.booking')),
                ('from_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swaps_from', to='bookings.room')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_swaps', to=settings.AUTH_USER_MODEL)),
                ('to_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swaps_to', to='bookings.room')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
