# Generated by Django 5.1.1 on 2025-10-26 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_enhanced_leave_management'),
        ('pgadmin', '0011_add_notice_period_to_pg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayWiseBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('share_no', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=15)),
                ('emergency_contact', models.CharField(max_length=15)),
                ('selfie', models.ImageField(blank=True, null=True, upload_to='daywise_bookings/selfies/')),
                ('document1', models.FileField(blank=True, null=True, upload_to='daywise_bookings/documents/')),
                ('document2', models.FileField(blank=True, null=True, upload_to='daywise_bookings/documents/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('purpose', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('payment_received', models.BooleanField(default=False)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_daywise_bookings', to=settings.AUTH_USER_MODEL)),
                ('pg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daywise_bookings', to='pgadmin.pg')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daywise_bookings', to='bookings.room')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
