# Generated by Django 5.1.1 on 2025-10-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_daywisebooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daywisebooking',
            name='document1',
        ),
        migrations.RemoveField(
            model_name='daywisebooking',
            name='document2',
        ),
        migrations.AddField(
            model_name='daywisebooking',
            name='aadhaar_doc1',
            field=models.FileField(blank=True, help_text='Aadhaar image 1 or PDF', null=True, upload_to='daywise_bookings/aadhaar/'),
        ),
        migrations.AddField(
            model_name='daywisebooking',
            name='aadhaar_doc2',
            field=models.FileField(blank=True, help_text='Aadhaar image 2 (if not PDF)', null=True, upload_to='daywise_bookings/aadhaar/'),
        ),
    ]
