# Generated by Django 5.1.1 on 2025-10-26 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0021_remove_daywisebooking_document1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='assigned_at',
            field=models.DateTimeField(blank=True, help_text='When room was assigned by admin', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='Admin who assigned the room', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('regular', 'Regular Monthly'), ('daywise', 'Day-wise/Short-term')], default='regular', help_text='Type of booking: regular monthly or day-wise short-term', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(blank=True, help_text='For day-wise bookings: check-out time', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='For day-wise bookings: specific payment amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_received',
            field=models.BooleanField(default=False, help_text='For day-wise bookings: payment received status'),
        ),
        migrations.AddField(
            model_name='booking',
            name='purpose',
            field=models.TextField(blank=True, help_text='For day-wise bookings: purpose of short stay'),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(blank=True, help_text='For day-wise bookings: check-in time', null=True),
        ),
        migrations.AddField(
            model_name='residentapplication',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text='Emergency contact number (for day-wise bookings)', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='joining_date',
            field=models.DateField(blank=True, help_text='Date tenant actually moved in; used to calculate rent days. For day-wise bookings, this is the start date.', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='leaving_date',
            field=models.DateField(blank=True, help_text='Date tenant left or will leave. For day-wise bookings, this is the end date.', null=True),
        ),
    ]
