# Generated by Django 5.1.1 on 2025-10-26 21:12

from django.db import migrations


def migrate_daywise_bookings(apps, schema_editor):
    """
    Migrate DayWiseBooking records to Booking model.
    For each DayWiseBooking:
    - Create a Booking with booking_type='daywise'
    - Create a ResidentApplication linked to the Booking
    - Map fields appropriately
    """
    DayWiseBooking = apps.get_model('bookings', 'DayWiseBooking')
    Booking = apps.get_model('bookings', 'Booking')
    ResidentApplication = apps.get_model('bookings', 'ResidentApplication')
    User = apps.get_model('auth', 'User')  # Django's default User model
    
    # Get or create a system user for day-wise bookings (non-registered guests)
    system_user, _ = User.objects.get_or_create(
        username='daywise_system',
        defaults={
            'email': 'daywise@system.local',
            'first_name': 'Day-wise',
            'last_name': 'System',
            'is_active': False,  # System account, not for login
        }
    )
    
    migrated_count = 0
    for daywise in DayWiseBooking.objects.all():
        # Create Booking
        booking = Booking.objects.create(
            user=system_user,  # Day-wise guests don't have user accounts
            room=daywise.room if daywise.room else daywise.pg.rooms.first(),  # Use assigned room or first room
            pg=daywise.pg,
            share_no=daywise.share_no if daywise.share_no else 1,
            booking_type='daywise',
            status=daywise.status,
            joining_date=daywise.start_date,  # Start date → joining date
            leaving_date=daywise.end_date,    # End date → leaving date
            start_time=daywise.start_time,
            end_time=daywise.end_time,
            purpose=daywise.purpose,
            payment_received=daywise.payment_received,
            payment_amount=daywise.payment_amount,
            assigned_at=daywise.assigned_at,
            assigned_by=daywise.assigned_by,
            created_at=daywise.created_at,
            updated_at=daywise.updated_at,
        )
        
        # Create ResidentApplication for the booking
        ResidentApplication.objects.create(
            user=system_user,
            booking=booking,
            pg=daywise.pg,
            room=booking.room,
            status='confirmed' if daywise.status == 'approved' else 'submitted',
            name=daywise.name,
            phone=daywise.mobile,
            emergency_contact=daywise.emergency_contact,
            email=f"daywise_{daywise.id}@guest.local",  # Dummy email for day-wise guests
            selfie_url='',  # Files were stored in media, URLs will be handled separately
            aadhaar_file_url='',
            aadhaar_file_url_2='',
        )
        
        migrated_count += 1
    
    if migrated_count > 0:
        print(f"Successfully migrated {migrated_count} day-wise bookings to Booking model")


def reverse_migration(apps, schema_editor):
    """Remove migrated day-wise bookings if rolling back"""
    Booking = apps.get_model('bookings', 'Booking')
    ResidentApplication = apps.get_model('bookings', 'ResidentApplication')
    
    # Delete all day-wise bookings and their applications
    daywise_bookings = Booking.objects.filter(booking_type='daywise')
    ResidentApplication.objects.filter(booking__in=daywise_bookings).delete()
    daywise_bookings.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0022_booking_assigned_at_booking_assigned_by_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),  # Standard Django auth migration
    ]

    operations = [
        migrations.RunPython(migrate_daywise_bookings, reverse_migration),
    ]
