# Generated by Django 5.1.1 on 2025-10-26 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0023_migrate_daywise_to_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DayWiseBooking',
        ),
    ]
