# Generated by Django 5.1.1 on 2025-10-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0024_remove_daywise_booking_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstatushistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('confirmed', 'Confirmed'), ('refill_requested', 'Re-Fill Requested'), ('resubmitted', 'Re-Submitted'), ('rejected', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='residentapplication',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='residentapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('confirmed', 'Confirmed'), ('refill_requested', 'Re-Fill Requested'), ('resubmitted', 'Re-Submitted'), ('rejected', 'Rejected')], default='submitted', max_length=20),
        ),
    ]
