# Generated by Django 5.1.1 on 2025-12-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0025_alter_applicationstatushistory_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='whatsapp_invite_sent',
            field=models.BooleanField(default=False, help_text='Whether WhatsApp group invite has been sent to this tenant'),
        ),
        migrations.AddField(
            model_name='booking',
            name='whatsapp_invite_sent_at',
            field=models.DateTimeField(blank=True, help_text='When WhatsApp invite was marked as sent', null=True),
        ),
    ]
