# Generated by Django 5.1.1 on 2026-07-11 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def detach_unassigned_pending_daywise(apps, schema_editor):
    Booking = apps.get_model('bookings', 'Booking')
    ResidentApplication = apps.get_model('bookings', 'ResidentApplication')
    affected_ids = list(Booking.objects.filter(
        booking_type='daywise',
        status='pending',
        assigned_by__isnull=True,
        assigned_at__isnull=True,
    ).values_list('id', flat=True))
    if affected_ids:
        ResidentApplication.objects.filter(booking_id__in=affected_ids).update(room=None)
        Booking.objects.filter(id__in=affected_ids).update(room=None, share_no=None)


def preserve_current_assignment_on_reverse(apps, schema_editor):
    Booking = apps.get_model('bookings', 'Booking')
    ResidentApplication = apps.get_model('bookings', 'ResidentApplication')
    Room = apps.get_model('bookings', 'Room')
    for booking in Booking.objects.filter(room__isnull=True):
        room = Room.objects.filter(pg_id=booking.pg_id).order_by('id').first()
        if room is None:
            raise RuntimeError('Cannot reverse day-wise assignment migration for a PG without rooms.')
        Booking.objects.filter(pk=booking.pk).update(room=room, share_no=1)
        ResidentApplication.objects.filter(booking_id=booking.pk).update(room=room)


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0026_whatsapp_invite_fields'),
        ('pgadmin', '0020_oldtenant_aadhaar_file_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='uniq_active_booking_per_user_per_pg',
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.room'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='share_no',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='residentapplication',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resident_applications', to='bookings.room'),
        ),
        migrations.RunPython(detach_unassigned_pending_daywise, preserve_current_assignment_on_reverse),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('booking_type', 'regular'), ('status__in', ['pending', 'approved'])), fields=('user', 'pg'), name='uniq_active_booking_per_user_per_pg'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('room__isnull', False), ('share_no__isnull', False)), models.Q(('booking_type', 'daywise'), ('status__in', ['pending', 'rejected'])), _connector='OR'), name='booking_assignment_required_unless_pending_daywise'),
        ),
    ]
